# Generated by Django 6.0.4 on 2026-05-07 05:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0016_metalrate'),
    ]

    operations = [
        migrations.CreateModel(
            name='MetalOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('metal_type', models.CharField(choices=[('gold_22k', 'Gold 22K'), ('gold_24k', 'Gold 24K'), ('silver_999', 'Silver 999')], max_length=20)),
                ('weight_label', models.CharField(max_length=20)),
                ('weight_grams', models.DecimalField(decimal_places=4, max_digits=10)),
                ('count', models.IntegerField()),
                ('rate_per_gram', models.DecimalField(decimal_places=2, max_digits=10)),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=12)),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=14)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='metal_orders', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
