# Generated by Django 4.2.11 on 2026-05-23 04:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0018_jewelryproduct_jewelryproductimage'),
    ]

    operations = [
        migrations.CreateModel(
            name='HomeBanner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slot', models.IntegerField(choices=[(1, 'Banner 1'), (2, 'Banner 2'), (3, 'Banner 3'), (4, 'Banner 4'), (5, 'Banner 5')], unique=True)),
                ('image', models.ImageField(upload_to='home_banners/')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['slot'],
            },
        ),
    ]
