# Generated by Django 4.2.11 on 2026-05-26 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0020_rename_weight_grams_jewelryproduct_cross_weight_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='jewelryproduct',
            name='gender',
            field=models.CharField(blank=True, choices=[('men', 'Men'), ('women', 'Women'), ('kids', 'Kids'), ('all', 'All')], default='all', max_length=10),
        ),
        migrations.AddField(
            model_name='jewelryproduct',
            name='occasion',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='jewelryproduct',
            name='wastage_charge',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='jewelryproduct',
            name='wedding_category',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
