# Generated by Django 4.2.11 on 2026-05-27 08:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0021_jewelryproduct_gender_jewelryproduct_occasion_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jewelryproduct',
            name='category',
            field=models.CharField(choices=[('rings', 'Rings'), ('necklaces', 'Necklaces'), ('bangles', 'Bangles'), ('bracelets', 'Bracelets'), ('earrings', 'Earrings'), ('chains', 'Chains'), ('coins', 'Coins')], max_length=20),
        ),
        migrations.AlterField(
            model_name='jewelryproduct',
            name='grade',
            field=models.CharField(blank=True, choices=[('22k', '22K'), ('24k', '24K'), ('999', '999'), ('', 'N/A')], max_length=10),
        ),
        migrations.AlterField(
            model_name='jewelryproduct',
            name='metal',
            field=models.CharField(choices=[('gold', 'Gold'), ('silver', 'Silver'), ('diamond', 'Diamond')], max_length=10),
        ),
    ]
