# Generated by Django 4.2.11 on 2026-06-01 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0025_jewelryproduct_original_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='metalrate',
            name='diamond_18k',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='metalrate',
            name='diamond_22k',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='metalrate',
            name='platinum_92',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='metalrate',
            name='gold_22k',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='metalrate',
            name='gold_24k',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='metalrate',
            name='silver_999',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
