# Generated by Django 4.2.11 on 2026-06-09 09:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0027_alter_jewelryproduct_grade_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='JewelryOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=200)),
                ('product_metal', models.CharField(max_length=20)),
                ('product_grade', models.CharField(blank=True, max_length=10)),
                ('product_category', models.CharField(max_length=20)),
                ('product_image_url', models.TextField(blank=True)),
                ('customer_name', models.CharField(max_length=200)),
                ('customer_phone', models.CharField(max_length=10)),
                ('customer_alt_phone', models.CharField(blank=True, max_length=10)),
                ('customer_dob', models.DateField(blank=True, null=True)),
                ('customer_anniversary', models.DateField(blank=True, null=True)),
                ('pincode', models.CharField(max_length=6)),
                ('address_line1', models.TextField()),
                ('address_line2', models.TextField(blank=True)),
                ('city', models.CharField(max_length=50)),
                ('state', models.CharField(max_length=50)),
                ('quantity', models.IntegerField(default=1)),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=12)),
                ('total_price', models.DecimalField(decimal_places=2, max_digits=14)),
                ('payment_method', models.CharField(choices=[('upi', 'UPI'), ('debit_card', 'Debit Card'), ('credit_card', 'Credit Card'), ('net_banking', 'Net Banking'), ('cash_on_delivery', 'Cash on Delivery'), ('emi', 'EMI')], max_length=30)),
                ('payment_status', models.CharField(default='pending', max_length=20)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('confirmed', 'Confirmed'), ('processing', 'Processing'), ('shipped', 'Shipped'), ('delivered', 'Delivered'), ('cancelled', 'Cancelled')], default='pending', max_length=20)),
                ('order_id', models.CharField(blank=True, max_length=30, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('product', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders', to='accounts.jewelryproduct')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='jewelry_orders', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
