# Generated by Django 6.0.6 on 2026-07-08 11:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0029_jewelryorder_razorpay_order_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='announcement',
            name='target_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='personal_announcements', to=settings.AUTH_USER_MODEL),
        ),
    ]
