# Generated by Django 6.0.6 on 2026-07-20 04:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0030_announcement_target_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='CoinRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('sent', 'Sent')], default='pending', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('requested_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='coin_requests_made', to=settings.AUTH_USER_MODEL)),
                ('requested_to', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='coin_requests_received', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='CoinRequestItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('metal_type', models.CharField(max_length=20)),
                ('weight_label', models.CharField(max_length=20)),
                ('weight_grams', models.DecimalField(decimal_places=4, max_digits=10)),
                ('qty', models.PositiveIntegerField()),
                ('request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='accounts.coinrequest')),
            ],
        ),
        migrations.CreateModel(
            name='CoinStock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('metal_type', models.CharField(max_length=20)),
                ('weight_label', models.CharField(max_length=20)),
                ('weight_grams', models.DecimalField(decimal_places=4, max_digits=10)),
                ('qty', models.PositiveIntegerField(default=0)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='coin_stock', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'metal_type', 'weight_label')},
            },
        ),
    ]
