# Generated by Django 6.0.6 on 2026-07-20 05:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0031_coinrequest_coinrequestitem_coinstock'),
    ]

    operations = [
        migrations.AddField(
            model_name='coinrequest',
            name='reject_reason',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='coinrequest',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('sent', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=10),
        ),
    ]
